### ISSUE TITLE
_grokparsefailure

### ISSUE THREAD

**Issue by mbaersch** [Michaelcgn/graylog_vagrant_demo#2]
Hi Michael, 

when I feed the demo with my logs, all GELF messages are tagged with *_grokparsefailure* and do not contain the expected fields. I tried out some random lines from my logs in Grok Debugger and they seem to match just fine against `%{COMBINEDAPACHELOG}`. 

I also changed my logstash.conf to look at the results as JSON and found nothing unusual. Here´s an example: 

```
{
 "message":"static.64.17.243.xxx.clients.your-server.de - - [10/Sep/2015:00:12:20 +0200] \"GET /impressum.html HTTP/1.1\" 200 12432 \"-\" \"Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/27.0.1453.xxx Safari/537.36\"",
 "@version":"1",
 "@timestamp":"2015-09-09T22:12:20.000Z",
 "host":"graylog",
 "path":"/var/work/logs/www.20150910",
 "type":"apache_access",
 "clientip":"static.64.17.243.xxx.clients.your-server.de",
 "ident":"-",
 "auth":"-",
 "timestamp":"10/Sep/2015:00:12:20 +0200",
 "verb":"GET",
 "request":"/impressum.html",
 "httpversion":"1.1",
 "response":"200",
 "bytes":"12432",
 "referrer":"\"-\"",
 "agent":"\"Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/27.0.1453.xxx Safari/537.36\"",
 "client_host":"static.64.17.243.xxx.clients.your-server.de"
}
```

But all messages in Gralylog unfortunately look more like this (even if it is a different example): 

```
client_host
%{clientip}

facility
gelf-rb

full_message
. - - [01/Sep/2015:08:41:41 +0200] "GET /images/template/bullet.png HTTP/1.1" 200 468 "https://www.gandke.de/css/responsive.css?v=2" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36"

level
6

message
. - - [01/Sep/2015:08:41:41 +0200] "GET /images/template/bullet.png HTTP/1.1" 200 468 "https://www.gandke.de/css/responsive.css?v=2" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36"

path
/var/work/logs/www.20150901

source
graylog

tags
_grokparsefailure

type
apache_access

version
1.0
```

It looks as if Graylog _only_ holds messages that contain lines from the logfile that do **not** match. And there are only 15 of them while the input receives about 60 msg/s...     

Can you tell me what´s wrong here? Or what type of samles I can provide to help you to reproduce my problem?  

Thanks, 

Markus

**Comment by Michaelcgn** [comment]
Can you try it with an real ip as client_ip and not an domain?

**Comment by mbaersch** [comment]
Logs did contain entries with a pure IP as well (like 194.187.168.xxx - and yes: there _are_ real numbers in the D Block, but I am too german to post the whole address :)) but that seems to make no difference. Just randomly picked a (bad) example.
